name: Deploy

on:
  workflow_dispatch:

concurrency: deploy

permissions:
  contents: read
  deployments: write

jobs:

  deploy:
    name: Deploy Worker
    runs-on: ubuntu-latest

    environment:
      name: production
      url: https://notify.ruddarr.com

    env:
      SENTRY_ORG: ruddarr
      SENTRY_PROJECT: apns

    steps:
      - name: Check out repository
        uses: actions/checkout@v6

      - name: Install dependencies
        run: npm install

      - name: Deploy Worker
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
        run: npm run deploy
